api:
  port: 8081
retriever:
  uniter:
    n_gpu: 1
    uniter_dir: ${env:UNITER_DATA_DIR}
    model_config: ${env:UNITER_MODEL_CONFIG}
    num_imgs: 1000
    batch_size: 50
    n_data_workers: 0
    fp16: True
    pin_mem: True
image_server:
  lighttp:
    https: false
    host: localhost
    port: 8082
    endpoint: /
