# run: CUDA_HOME=/usr/local/cuda-10.1 conda env create -v --file environment.yaml
# for debug use -vv or -vvv
name: mt
channels:
- pytorch
- conda-forge
dependencies:
- python==3.7
- pip
- mpi4py~=3.0.3
- pytorch~=1.7.0
- torchvision~=0.8.1
- cudatoolkit=10.1
- pip:
    # general requirements
    - fastapi~=0.61.2
    - pydantic~=1.7.2
    - uvicorn~=0.12.2
    - pytest~=6.1.2
    - requests~=2.24.0
    - omegaconf~=2.0.4
    - aiofiles~=0.6.0

    # uniter requirements
    - tqdm~=4.51.0
    - tensorboardX~=2.1
    - pandas~=1.1.4
    - numpy~=1.19.4
    - lmdb~=1.0.0
    - lz4~=3.1.0
    - horovod~=0.20.3
    - msgpack~=1.0.0
    - msgpack-numpy~=0.4.7.1
    - cytoolz~=0.11.0
    - pytorch-pretrained-bert~=0.6.2
    # We have to install APEX separately or the line below will take FOREVER....
    # - git+https://github.com/NVIDIA/apex --install-option="--no-cache-dir --global-option='--cpp_ext' --global-option='--cuda_ext'"